export default {
  TOGGLE_MENU_ON_MOBILE: 'TOGGLE_MENU_ON_MOBILE',
  SELECT_WINDOW_TYPE: 'SELECT_WINDOW_TYPE',
  SET_WINDOW_WIDTH: 'SET_WINDOW_WIDTH',
  SET_WINDOW_HEIGHT: 'SET_WINDOW_HEIGHT',
  SET_SASHES_NUMBER: 'SET_SASHES_NUMBER',
  SET_PRICE: 'SET_PRICE',
  OPEN_PRICE_MODAL: 'OPEN_PRICE_MODAL',
  CLOSE_PRICE_MODAL: 'CLOSE_PRICE_MODAL',
  OPEN_RESPONSE_MODAL: 'OPEN_RESPONSE_MODAL',
  CLOSE_RESPONSE_MODAL: 'CLOSE_RESPONSE_MODAL',
  SET_RESPONSE: 'SET_RESPONSE',
  SPINNER_ON: 'SPINNER_ON',
  SPINNER_OFF: 'SPINNER_OFF'
};